module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    CATEGORY_COLLECTION:'category',
    SUB_CATEGORY_COLLECTION:'subcategory',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    WISHLIST_COLLECTION:'wishlist',
    COUPON_COLLECTION:'coupon',
    ADDRESS_COLLECTION:'address',
    CAROUSEL_COLLECTION:'carousel'
}